/* bsky-cards.js — Bluesky post-card overlay for the presentation.
 *
 * Reads the JSON embedded in the slide as <script id="bsky-posts"
 * type="application/json"> and builds <article class="bsky-card"> elements
 * inside the slide's <div class="bsky-field">. The play order is a seeded
 * (deterministic) shuffle, with same-author posts never back to back. The
 * slide opens with four cards already in place (no fade-in); then one new
 * card every 3s — each card fades out over 5s once the fourth newer card
 * has arrived, so four coexist on screen, and the last four stay up until
 * the slide is left. Placement is a cell grid sized so concurrent cards
 * never overlap. The driver only runs while the slide is `.present`.
 *
 * Styling lives in css/theme-override.css (§ "Bluesky post cards").
 */

(() => {
  const dataEl = document.getElementById("bsky-posts");
  if (!dataEl) return;
  const data = JSON.parse(dataEl.textContent);
  const field = document.querySelector(".bsky-field");
  if (!field) return;
  const section = field.closest("section");
  // The slide ships with a static render of the animation's final frame
  // (img/anti-ai-posts-fallback.png, regenerated by
  // tools/make-bsky-fallback.py) shown when this driver can't run. The
  // cards are up, so swap it out.
  document.querySelector(".bsky-fallback-img")?.remove();

  // Seeded PRNG (mulberry32) — the shuffle below and the scatter jitter in
  // place() are random on every load but identical across runs.
  const SEED = 0x9e3779b9;
  const rng = ((seed) => () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  })(SEED);

  // Fisher–Yates shuffle — the posts play in a fixed random order.
  const posts = [...data.posts];
  for (let i = posts.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [posts[i], posts[j]] = [posts[j], posts[i]];
  }

  // Then separate consecutive posts by the same author, so no two cards on
  // screen back to back share a byline. Swap each conflict with the next
  // post whose author differs on both sides of the swap.
  for (let i = 1; i < posts.length; i++) {
    if (posts[i].author.handle === posts[i - 1].author.handle) {
      const j = posts.findIndex(
        (p, k) =>
          k > i &&
          p.author.handle !== posts[i - 1].author.handle &&
          (k + 1 === posts.length ||
            posts[k + 1].author.handle !== posts[i].author.handle),
      );
      if (j > 0) [posts[i], posts[j]] = [posts[j], posts[i]];
    }
  }

  const cards = posts.map((post) => {
    const card = document.createElement("article");
    card.className = "bsky-card";
    const head = document.createElement("header");
    const who = document.createElement("div");
    who.className = "bsky-who";
    const meta = document.createElement("span");
    meta.className = "bsky-meta";
    meta.textContent = "@" + post.author.handle + " · " + post.date;
    who.append(meta);
    head.append(who);
    const body = document.createElement("p");
    body.textContent = post.text;
    card.append(head, body);
    return card;
  });
  cards.forEach((c) => field.appendChild(c));

  // Per-card scatter nudges, from the same seeded stream, so the grid
  // doesn't read as a grid but stays identical across runs.
  const jitter = cards.map(() => [rng(), rng()]);

  // Lay the cards out on a cell grid with margins so neighbours never
  // overlap: cells are sized from the widest/tallest card, and card i takes
  // cell i % slots — so the (up to) six cards that can be on screen at once
  // (four solid + up to two mid-fade) always sit in different cells; only
  // long-gone cards reuse one. Deterministic nudges keep it from looking
  // like a grid. Cards have flex height, so sizes are only known at layout
  // time — re-run on resize/activation.
  const GAP = 24;
  const place = () => {
    const fw = field.clientWidth,
      fh = field.clientHeight;
    if (!fw || !fh) return; // slide not laid out yet
    const w = Math.max(...cards.map((c) => c.offsetWidth));
    const h = Math.max(...cards.map((c) => c.offsetHeight));
    const cols = Math.max(1, Math.floor((fw + GAP) / (w + GAP)));
    const rows = Math.max(2, Math.floor((fh + GAP) / (h + GAP)));
    const slots = cols * rows;
    const cellW = fw / cols,
      cellH = fh / rows;
    cards.forEach((card, i) => {
      const col = (i % slots) % cols;
      const row = Math.floor((i % slots) / cols);
      const [jx, jy] = jitter[i];
      const slackX = Math.max(0, cellW - w);
      const slackY = Math.max(0, cellH - card.offsetHeight);
      // Final safety clamp: whatever the measurements said when the grid
      // was sized (e.g. before webfonts finished loading and text rewrapped
      // taller), never let a card past the field edge — instead of clipping
      // it, shift it inward.
      const x = Math.min(
        col * cellW + slackX * (0.1 + 0.8 * jx),
        fw - card.offsetWidth,
      );
      const y = Math.min(
        row * cellH + slackY * (0.1 + 0.8 * jy),
        fh - card.offsetHeight,
      );
      card.style.left = Math.max(0, x) + "px";
      card.style.top = Math.max(0, y) + "px";
    });
    // Deterministic layout trace: one line per distinct placement (the
    // seeded shuffle and jitter make positions reproducible run to run —
    // tools/make-bsky-fallback.py renders its static frame from the same
    // math, and this line is how you check the two agree).
    const layout = cards
      .map(
        (c, i) =>
          `${i} ${posts[i].author.handle} ` +
          `${c.style.left},${c.style.top} ${c.offsetWidth}x${c.offsetHeight}`,
      )
      .join(" | ");
    if (layout !== lastLayout) console.log(`bsky layout: ${layout}`);
    lastLayout = layout;
  };
  let lastLayout = "";
  place();
  // Card sizes change after place() runs (webfonts swapping in rewraps the
  // text), so re-place whenever any card or the field actually resizes.
  if (typeof ResizeObserver === "function") {
    const ro = new ResizeObserver(place);
    cards.forEach((c) => ro.observe(c));
    ro.observe(field);
  } else {
    addEventListener("resize", place);
  }
  if (document.fonts) document.fonts.ready.then(place);

  const STAGGER = 3000,
    OUT = 5000,
    VISIBLE = 4; // cards up at a time; each fades 5s once 4 newer have come
  const show = (card, instant = false) => {
    card.style.transitionDuration = instant ? "0ms" : "450ms";
    card.classList.add("bsky-show");
  };
  const fade = (card) => {
    card.style.transitionDuration = OUT + "ms";
    card.classList.remove("bsky-show");
  };
  const reset = () => {
    for (const c of cards) {
      c.style.transitionDuration = "0ms";
      c.classList.remove("bsky-show");
    }
  };
  let idx = 0,
    timer = null;
  const tick = () => {
    if (idx >= cards.length) {
      clearInterval(timer);
      timer = null;
      return; // the last VISIBLE cards stay until the slide is left
    }
    show(cards[idx]);
    const dying = idx - VISIBLE;
    if (dying >= 0 && dying < cards.length - VISIBLE) fade(cards[dying]);
    idx++;
  };
  const start = () => {
    if (timer) return;
    reset();
    place(); // the slide is laid out now; size the cells against reality
    idx = 0;
    // Open with four cards already in place (no fade-in), then one new
    // card every 3s until the deck runs out — the last four stay up.
    for (let k = 0; k < VISIBLE && idx < cards.length; k++)
      show(cards[idx++], true);
    timer = setInterval(tick, STAGGER);
  };
  const stop = () => {
    clearInterval(timer);
    timer = null;
  };
  const active = () => section.classList.contains("present");
  const entered = (slide) => slide === section || slide.contains(section);
  document.addEventListener("slidechanged", (e) =>
    entered(e.target) ? start() : stop(),
  );
  document.addEventListener("ready", () => active() && start());
  setTimeout(() => active() && start(), 800);
})();
