# frozen_string_literal: true

# bsky-macro.rb — native `bsky-cards::URL,URL,...[]` block macro: the
# Bluesky post-card overlay slide, with post data fetched live at
# conversion time from the public Bluesky AppView. No JSON on disk: the
# macro targets in presentation.adoc are the source of truth, and a post
# deleted from Bluesky silently drops out of the deck (staleness is a
# feature). Load it with:  asciidoctor-revealjs -r tools/bsky-macro.rb
#
# Emits the same markup the (since-removed) static include produced:
# .bsky-field + static fallback frame + posts JSON + js/bsky-cards.js.
# The fallback PNG is regenerated by tools/make-bsky-fallback.py
# (`make fallback`). Styling lives in css/theme-override.css
# (§ "Bluesky post cards").

raise 'bsky-macro.rb must be required through asciidoctor (-r tools/bsky-macro.rb)' unless defined? Asciidoctor

require 'cgi'
require 'date'
require 'json'
require 'net/http'
require 'uri'

module Bsky
  APPVIEW = 'https://public.api.bsky.app/xrpc'
  FALLBACK_IMG = '../img/anti-ai-posts-fallback.png'
  DRIVER_JS = '../js/bsky-cards.js'

  module_function

  def get(path, params)
    uri = URI("#{APPVIEW}/#{path}?#{params}")
    JSON.parse(Net::HTTP.get(uri))
  end

  def did_for(handle)
    get('com.atproto.identity.resolveHandle', "handle=#{handle}")['did'] ||
      get('app.bsky.actor.getProfile', "actor=#{handle}")['did'] or
      raise %(unable to resolve handle: #{handle})
  end

  def at_uri(url)
    m = url.match(%r{\Ahttps://bsky\.app/profile/([^/]+)/post/([^/?#]+)\z})
    raise %(not a bsky.app post URL: #{url}) unless m
    "at://#{did_for(m[1])}/app.bsky.feed.post/#{m[2]}"
  end

  # Posts as {url:, author:{handle,displayName,avatar}, date:, text:,
  # likes:, reposts:} — deleted/unfetchable posts are dropped.
  def posts(urls)
    uris = urls.to_h { |u| [at_uri(u), u] }
    found = get('app.bsky.feed.getPosts', 'uris=' + uris.keys.join('&uris='))
    Array(found['posts']).filter_map do |p|
      url = uris[p['uri']]
      next unless url
      date = DateTime.parse(p['record']['createdAt'])
      {
        'url' => url,
        'author' => {
          'handle' => p['author']['handle'],
          'displayName' => p['author']['displayName'],
          'avatar' => p['author']['avatar'],
        },
        'date' => date.strftime('%b %-d, %Y'),
        'text' => p['record']['text'],
        'likes' => p['likeCount'],
        'reposts' => p['repostCount'],
      }
    end
  end
end

Asciidoctor::Extensions.register do
  block_macro :"bsky-cards" do
    process do |parent, target, attrs|
      urls = target.split(',').map(&:strip).reject(&:empty?)
      posts = JSON.generate({ 'posts' => Bsky.posts(urls) })
      html = <<~HTML
        <div class="bsky-field" aria-hidden="true"></div>
        <img class="bsky-fallback-img" src="#{Bsky::FALLBACK_IMG}"
             alt="A grid of Bluesky posts criticizing generative AI">
        <script id="bsky-posts" type="application/json">#{posts}</script>
        <script src="#{Bsky::DRIVER_JS}"></script>
      HTML
      create_block parent, :pass, html, attrs || {}
    end
  end
end
