= What Technologists Owe Creatives
Joey Carpinelli <joseph.carpinelli@icloud.com>

// GOAL: introduce the talk

[.notes]
--
. I'm so thankful to be here for the first time at the Monktoberfest.
. I want to talk about technologists and creatives.
. I care deeply about both of these communities.
--

== Technologists

// GOAL: introduce myself; introduce and define the term "technologist"

[.notes]
--
. I'm proud to be a technologist today, but the word mostly felt like an obstacle on the way to engineer for most of my career so far.
. My first pay stub as a full-time engineer read _aerospace technologist_.
. The U.S. Government won't call you an engineer unless you're formally certified as a _Professional Engineer_.
. As I did the job, though, I grew to love the word.
. It's both more specific and more expansive than the word _engineer_.
. The word _technologist_ gets to the _what_ of your work much: we're building technology.
. I also don't think you need to be an engineer to be a technologist.
. For the purposes of this talk, you're a technologist if you work with or support the development of emerging technologies.
. That includes non-technical roles within companies, theorists, and practitioners.
. If you quibble with that definition, that's fine, but there's not currently a Wikipedia page for _technologist_.
--

== Creatives

// GOAL: introduce my connections to creatives; introduce and define the term "creative"

[.notes]
--
. I love creatives; in some cases, literally.
. My wife is a creative writer, and we were just married in June.
. Other members of my family are writers, animators, and filmmakers.
. I use the word _creative_ and not _artist_ because I think their relationship is similar to _technologist_ and _engineering_.
. Creatives are those for who creativity is the point.
. They could be making art, but for the purposes of this talk, they could also be creating ad copy.
--

== Creatives

// GOAL:
